// AUTO-GENERATED by scripts/generateServerSeed.js. Do not edit by hand.
// 正本: assets/characters/character_master.json (+ rarity-overrides.json)。app catalog と同一ソース。
// 初期リリース母集団＝基本4ワールド ∩ 承認済みアセット(hasImage)。

export type SeedCharacter = { id: string; name: string; rarity: string; world: string };

export const SEED_CHARACTERS: SeedCharacter[] = [
  {
    "id": "ground_aardvark",
    "name": "ツチブタン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_alpaca",
    "name": "モコアルパ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_anteater",
    "name": "アリクイノ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_armadillo",
    "name": "アルマジロロ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_badger",
    "name": "アナグマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_bear",
    "name": "コグマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_bison",
    "name": "バイソン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_camel",
    "name": "ラクダム",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_cat",
    "name": "ヒカリネコ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_chameleon",
    "name": "カメレオンヌ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_cheetah",
    "name": "チータス",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_chimpanzee",
    "name": "チンパル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_cow",
    "name": "ウシモー",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_deer",
    "name": "コモレビシカ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_dog",
    "name": "モリイヌ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_donkey",
    "name": "ロバロン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_elephant",
    "name": "ゾウノコ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_ferret",
    "name": "フェレッタ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_fox",
    "name": "ユキギツネ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_gecko",
    "name": "ヤモリン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_giraffe",
    "name": "キリンネ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_goat",
    "name": "ヤギノコ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_gorilla",
    "name": "ゴリマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_hamster",
    "name": "ハナハム",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_hedgehog",
    "name": "ハリネズン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_horse",
    "name": "ウマカゼ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_hyena",
    "name": "ハイエニャ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_iguana",
    "name": "イグアロン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_jaguar",
    "name": "ジャガロン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_kangaroo",
    "name": "カンガルン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_koala",
    "name": "コアラン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_lemur",
    "name": "キツネザルン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_leopard",
    "name": "ヒョウテン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_lion",
    "name": "コライオン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_lizard",
    "name": "リクトカゲ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_llama",
    "name": "ラマロン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_mandrill",
    "name": "マンドリルン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_marmot",
    "name": "マーモル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_marten",
    "name": "テンテン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_meerkat",
    "name": "ミーアミィ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_mole",
    "name": "モグリット",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_monkey",
    "name": "サルッコ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_moose",
    "name": "ムースン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_mouse",
    "name": "ドングリネズ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_okapi",
    "name": "オカピン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_orangutan",
    "name": "オランゴ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_panda",
    "name": "パンダル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_pangolin",
    "name": "センザンコ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_porcupine",
    "name": "ヤマアラシン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_prairie_dog",
    "name": "プレリード",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_rabbit",
    "name": "ツキウサ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_raccoon",
    "name": "ホシアライ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_raccoon_dog",
    "name": "マメタヌキ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_rare_fenrir",
    "name": "フェンリル",
    "rarity": "legendary",
    "world": "ground"
  },
  {
    "id": "ground_rare_tsuchinoko",
    "name": "ツチノコ",
    "rarity": "legendary",
    "world": "ground"
  },
  {
    "id": "ground_rare_underground_dweller",
    "name": "地底人",
    "rarity": "legendary",
    "world": "ground"
  },
  {
    "id": "ground_rare_white_tiger",
    "name": "白虎",
    "rarity": "rare",
    "world": "ground"
  },
  {
    "id": "ground_rare_yeti",
    "name": "イエティ",
    "rarity": "legendary",
    "world": "ground"
  },
  {
    "id": "ground_red_panda",
    "name": "レッサン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_reindeer",
    "name": "トナカイン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_rhinoceros",
    "name": "サイガン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_serow",
    "name": "カモシカゼ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_sheep",
    "name": "ツノヒツジ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_skunk",
    "name": "スカンクー",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_sloth",
    "name": "ナマケロン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_snake",
    "name": "ヘビマキ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_squirrel",
    "name": "コノハリス",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_tapir",
    "name": "バクミィ",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_tiger",
    "name": "トラマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_vicuna",
    "name": "ビクーニャル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_weasel",
    "name": "イタチル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_wild_boar",
    "name": "イノマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_wolf",
    "name": "オオカミン",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "ground_zebra",
    "name": "シマウマル",
    "rarity": "normal",
    "world": "ground"
  },
  {
    "id": "sky_bat",
    "name": "コウモリン",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_cockatoo",
    "name": "オウムン",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_crane",
    "name": "ツルミヤ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_crow",
    "name": "カラスケ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_eagle",
    "name": "ワシノスケ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_flamingo",
    "name": "フラミン",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_hawk",
    "name": "タカマル",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_ostrich",
    "name": "ダチョラン",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_owl",
    "name": "フクロウル",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_parakeet",
    "name": "インコロ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_peacock",
    "name": "クジャックン",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_pigeon",
    "name": "ハトポッポ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_sparrow",
    "name": "スズメル",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_swallow",
    "name": "ツバメロ",
    "rarity": "normal",
    "world": "sky"
  },
  {
    "id": "sky_swan",
    "name": "ハクチョル",
    "rarity": "normal",
    "world": "sky"
  }
];
