/**
 * 新しいワールド構成のキャラクターデータを生成する。
 *
 * 入力:
 *   - assets/characters/character_master.json   … Character.xlsx から抽出した原本
 *       { "<world>": [ { no, name(キャラ名), speciesJa(和名), speciesEn(英名), rarity, status } ... ] }
 *   - assets/characters/<world>/<rarity>/<英名>.png または <world>/<英名>/<英名>.png … 実画像（存在するものだけ）
 *
 * 出力:
 *   - src/data/characterCatalog.generated.ts   … CATALOG_CHARACTERS / CATALOG_NORMALS / CATALOG_RARES / CATALOG_LEGENDARIES
 *   - src/assets/characterImages.generated.ts  … 実在PNGだけを static require する画像マニフェスト
 *
 * 方針:
 *   - 構築ロジックは scripts/catalogBuild.js（純粋・テスト可能）に集約。ここは file 書き出しとサムネ生成のみ。
 *   - Metro は動的requireできないので、画像は存在するものだけを静的requireする（欠損でバンドルが壊れない）。
 *   - 画像未生成のキャラも図鑑の枠として残す（hasImage=false）。
 */
const fs = require("fs");
const path = require("path");

const { buildCatalog, loadClassification } = require("./catalogBuild");
const { assertGenerationSafe } = require("./masterGuards");

const root = path.join(__dirname, "..");
const charactersDir = path.join(root, "assets", "characters");
const masterPath = path.join(charactersDir, "character_master.json");
const catalogOut = path.join(root, "src", "data", "characterCatalog.generated.ts");
const imagesOut = path.join(root, "src", "assets", "characterImages.generated.ts");

const toPosix = (value) => value.split(path.sep).join("/");

const master = JSON.parse(fs.readFileSync(masterPath, "utf8"));
const classification = loadClassification(charactersDir);
// secrets は通常 catalog に出さない（秘匿）。future/inactive/qa も初期リリース catalog に出さない。
const built = buildCatalog({ root, charactersDir, master, classification });

// Phase 0 ガード：world混入 / 空欄・未知rarity / legendary潰れ / ID重複rarity / initial件数変動 / initial未登録ID を生成前に検出する。
assertGenerationSafe("gen:catalog", { master, classification, built });

// release gate：initial なのに画像が無い（missing）場合、既定では生成を中止して既存の生成物を壊さない（§14/§26）。
// hasImage で releaseStatus を降格しない。欠損は release gate（validate:release-assets）で失敗させる。
const missing = built.missingInitialAssets;
const allowIncomplete = process.env.WORLDAWN_ALLOW_INCOMPLETE === "1";
if (missing.length > 0) {
  console.error(`[gen:catalog] initial だが画像が無いキャラが ${missing.length} 体（future へ降格しません）:`);
  for (const m of missing) console.error(`  - ${m.id} (${m.name} / ${m.speciesEn}) [${m.world}/${m.rarity}] 期待パス: ${m.expectedPaths[0]}`);
  if (!allowIncomplete) {
    console.error("[gen:catalog] 中止：4画像を配置してから再実行してください（WORLDAWN_ALLOW_INCOMPLETE=1 で 85体の安全ビルドを生成）。");
    process.exit(2);
  }
  console.warn("[gen:catalog] WORLDAWN_ALLOW_INCOMPLETE=1：画像がある initial のみで安全ビルドを生成します。");
}
// 生成物は「initial かつ画像あり（=buildable）」のみ。壊れた require を含めない。
const buildable = (arr) => arr.filter((c) => c.releaseStatus === "initial" && c.hasImage);
const characters = buildable(built.characters);
const rares = buildable(built.rares);
const legendaries = buildable(built.legendaries);
const initialIds = new Set([...characters, ...rares, ...legendaries].map((c) => c.id));
const imageEntries = built.imageEntries.filter((e) => initialIds.has(e.id));

const THUMB_MAX = 256; // 図鑑グリッド表示用サムネの最大辺(px)。表示は110px前後だがRetina/拡大に余裕を持たせる。
const thumbsDir = path.join(root, "assets", "thumbs");

// 大きな原画(1024px級)を図鑑用の小さいサムネに縮小する。原画より新しいサムネがあればスキップ。
const buildThumbnails = async (entries) => {
  const { Jimp } = require("jimp");
  fs.mkdirSync(thumbsDir, { recursive: true });
  const out = [];
  let made = 0;
  for (const e of entries) {
    const outAbs = path.join(thumbsDir, `${e.id}.png`);
    try {
      const srcStat = fs.statSync(e.abs);
      const fresh = fs.existsSync(outAbs) && fs.statSync(outAbs).mtimeMs >= srcStat.mtimeMs;
      if (!fresh) {
        const img = await Jimp.read(e.abs);
        const { width, height } = img.bitmap;
        const scale = THUMB_MAX / Math.max(width, height);
        if (scale < 1) {
          img.resize({ w: Math.max(1, Math.round(width * scale)), h: Math.max(1, Math.round(height * scale)) });
        }
        await img.write(outAbs);
        made += 1;
      }
      out.push({ id: e.id, requirePath: "../../" + toPosix(path.relative(root, outAbs)) });
    } catch (err) {
      console.warn(`  thumb skip ${e.id}: ${err.message}`);
    }
  }
  console.log(`thumbnails: ${out.length} ready (${made} regenerated)`);
  return out;
};

// ---------- write catalog ----------
const catalogLines = [];
catalogLines.push("// AUTO-GENERATED by scripts/generateCharacterData.js. Do not edit by hand.");
catalogLines.push("// worldGroup 構成のキャラクターメタデータ（画像requireは characterImages.generated.ts）。");
catalogLines.push("");
catalogLines.push("/**");
catalogLines.push(" * 図鑑上の分類。表示・説明文の出し分けにのみ使う。");
catalogLines.push(" * NORMAL=現生生物の通常形態 / RARE=実在する希少形態（白変種等） /");
catalogLines.push(" * LEGEND=絶滅生物 / SECRET=神話・伝承・空想・SF上の生物。");
catalogLines.push(" * 抽選・出現確率・解放条件は従来どおり rarity を参照し、この値へは依存しない。");
catalogLines.push(" */");
catalogLines.push('export type DexClass = "NORMAL" | "RARE" | "LEGEND" | "SECRET";');
catalogLines.push("");
catalogLines.push("export type CatalogCharacter = {");
catalogLines.push("  id: string;");
catalogLines.push("  realmGroup: string;");
catalogLines.push("  worldGroup: string;");
catalogLines.push("  no: number;");
catalogLines.push("  name: string;");
catalogLines.push("  speciesJa: string;");
catalogLines.push("  speciesEn: string;");
catalogLines.push("  hasImage: boolean;");
catalogLines.push("  releaseStatus: string;");
catalogLines.push("  /** 図鑑上の分類（表示専用）。抽選・確率・解放条件へは影響しない。 */");
catalogLines.push("  dexClass: DexClass;");
catalogLines.push("  status: string;");
catalogLines.push("  description: string;");
catalogLines.push("};");
catalogLines.push("");
catalogLines.push("export type CatalogRare = {");
catalogLines.push("  id: string;");
catalogLines.push("  realmGroup: string;");
catalogLines.push("  worldGroup: string;");
catalogLines.push("  no: number;");
catalogLines.push("  name: string;");
catalogLines.push("  speciesJa: string;");
catalogLines.push("  speciesEn: string;");
catalogLines.push("  hasImage: boolean;");
catalogLines.push("  releaseStatus: string;");
catalogLines.push("  /** 図鑑上の分類（表示専用）。抽選・確率・解放条件へは影響しない。 */");
catalogLines.push("  dexClass: DexClass;");
catalogLines.push("  description: string;");
catalogLines.push("};");
catalogLines.push("");
catalogLines.push(`export const CATALOG_CHARACTERS: CatalogCharacter[] = ${JSON.stringify(characters, null, 2)};`);
catalogLines.push("");
// CATALOG_NORMALS は CATALOG_CHARACTERS の別名（normal 一覧）。段3で normal/rare/legendary を明示分離。
catalogLines.push("export const CATALOG_NORMALS: CatalogCharacter[] = CATALOG_CHARACTERS;");
catalogLines.push("");
catalogLines.push(`export const CATALOG_RARES: CatalogRare[] = ${JSON.stringify(rares, null, 2)};`);
catalogLines.push("");
// 伝説キャラ（段3）。UIは「そのワールドのnormalコンプリート後のみ」表示すること（未解放時は一切示唆しない）。
catalogLines.push(`export const CATALOG_LEGENDARIES: CatalogRare[] = ${JSON.stringify(legendaries, null, 2)};`);
catalogLines.push("");
fs.writeFileSync(catalogOut, catalogLines.join("\n"), "utf8");

// ---------- write image manifest（サムネ生成を含むため async） ----------
(async () => {
  const thumbEntries = await buildThumbnails(imageEntries);

  const imgLines = [];
  imgLines.push("// AUTO-GENERATED by scripts/generateCharacterData.js. Do not edit by hand.");
  imgLines.push("// 実在するPNGだけを static require（欠損画像はキーごと存在しない）。");
  imgLines.push("// CHARACTER_IMAGES=原画（個体詳細/結果用）、CHARACTER_THUMBS=図鑑グリッド用の縮小版。");
  imgLines.push('import type { ImageSourcePropType } from "react-native";');
  imgLines.push("");
  imgLines.push("export const CHARACTER_IMAGES: Record<string, ImageSourcePropType> = {");
  for (const e of imageEntries) {
    imgLines.push(`  ${JSON.stringify(e.id)}: require(${JSON.stringify(e.requirePath)}),`);
  }
  imgLines.push("};");
  imgLines.push("");
  imgLines.push("export const CHARACTER_THUMBS: Record<string, ImageSourcePropType> = {");
  for (const e of thumbEntries) {
    imgLines.push(`  ${JSON.stringify(e.id)}: require(${JSON.stringify(e.requirePath)}),`);
  }
  imgLines.push("};");
  imgLines.push("");
  imgLines.push("export const getCharacterImage = (id: string): ImageSourcePropType | undefined => CHARACTER_IMAGES[id];");
  imgLines.push("");
  imgLines.push("export const hasCharacterImage = (id: string): boolean => Boolean(CHARACTER_IMAGES[id]);");
  imgLines.push("");
  imgLines.push("// 図鑑用サムネ。無ければ原画へフォールバックできるよう undefined を返す。");
  imgLines.push("export const getCharacterThumb = (id: string): ImageSourcePropType | undefined =>");
  imgLines.push("  CHARACTER_THUMBS[id] ?? CHARACTER_IMAGES[id];");
  imgLines.push("");
  fs.writeFileSync(imagesOut, imgLines.join("\n"), "utf8");

  // ---------- summary ----------
  const byWorld = {};
  for (const c of characters) {
    byWorld[c.worldGroup] = byWorld[c.worldGroup] || { total: 0, img: 0 };
    byWorld[c.worldGroup].total += 1;
    if (c.hasImage) byWorld[c.worldGroup].img += 1;
  }
  console.log("Generated:", path.relative(root, catalogOut), "&", path.relative(root, imagesOut));
  console.log("characters:", characters.length, "rares:", rares.length, "legendaries:", legendaries.length, "images bundled:", imageEntries.length);
  for (const [wg, s] of Object.entries(byWorld)) {
    console.log(`  ${wg}: ${s.img}/${s.total} images`);
  }
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
