const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const charactersDir = path.join(root, "assets", "characters");
const outFile = path.join(root, "src", "assets", "monsterIndividualImages.ts");

const speciesKeys = [
  "dog",
  "cat",
  "squirrel",
  "frog",
  "bear",
  "fox",
  "tanuki",
  "lion",
  "elephant",
  "giraffe",
  "whale",
  "dolphin",
  "shark",
  "penguin",
  "sparrow",
  "crow",
  "owl",
  "turtle",
  "crocodile",
  "snake",
  "beetle",
  "stag_beetle",
  "deer",
  "rabbit",
  "jellyfish",
  "mole",
  "ostrich",
  "eagle",
  "human",
  "gorilla",
  "monkey",
  "hippo",
  "horse",
  "koala",
  "hamster"
];

const variantKeys = [
  "asatsuyu",
  "youkou",
  "tasogare",
  "tsukikage",
  "harukaze",
  "natsuhikari",
  "momiji",
  "yukitomoshi",
  "common",
  "uncommon",
  "rare",
  "legend"
];

const ignoredRootDirs = new Set(["old", "backup"]);

const toPosix = (value) => value.split(path.sep).join("/");

const walkPngs = (dir, rootDepth = 0) => {
  if (!fs.existsSync(dir)) {
    return [];
  }

  const files = [];
  for (const entry of fs.readdirSync(dir)) {
    const absolutePath = path.join(dir, entry);
    const stat = fs.statSync(absolutePath);

    if (stat.isDirectory()) {
      if (rootDepth === 0 && ignoredRootDirs.has(entry)) {
        continue;
      }
      files.push(...walkPngs(absolutePath, rootDepth + 1));
      continue;
    }

    if (stat.isFile() && entry.toLowerCase().endsWith(".png")) {
      files.push(absolutePath);
    }
  }

  return files;
};

const getGeneratedFiles = () => {
  const pngsByName = new Map();
  for (const absolutePath of walkPngs(charactersDir)) {
    const fileName = path.basename(absolutePath).toLowerCase();
    if (!pngsByName.has(fileName)) {
      pngsByName.set(fileName, absolutePath);
    }
  }

  const generated = [];
  for (const speciesKey of speciesKeys) {
    for (const variantKey of variantKeys) {
      const imageKey = `${speciesKey}_${variantKey}`;
      const fileName = `${imageKey}.png`;
      const absolutePath = pngsByName.get(fileName.toLowerCase());

      if (absolutePath) {
        generated.push({
          imageKey,
          requirePath: "../../" + toPosix(path.relative(root, absolutePath))
        });
      }
    }
  }

  return generated;
};

const generated = getGeneratedFiles();
const lines = [
  'import type { ImageSourcePropType } from "react-native";',
  "",
  'import { INDIVIDUAL_VARIANT_KEYS, type IndividualVariant } from "../data/individualVariants";',
  'import type { IndividualVariantKey } from "../types/monster";',
  "",
  "export type MonsterIndividualImageKey = `${string}_${IndividualVariantKey}`;",
  "",
  "export const makeIndividualImageKey = (",
  "  speciesKey: string,",
  "  variantKey: IndividualVariantKey",
  "): MonsterIndividualImageKey => `${speciesKey}_${variantKey}` as MonsterIndividualImageKey;",
  "",
  "// This file is generated by scripts/generateMonsterImages.js.",
  "// It scans assets/characters/<world>/<English>/ recursively and ignores old/backup.",
  "// Only existing PNGs are required so Metro never tries to bundle a missing file.",
  "export const monsterIndividualImages: Partial<Record<MonsterIndividualImageKey, ImageSourcePropType>> = {"
];

for (const item of generated) {
  lines.push(`  ${JSON.stringify(item.imageKey)}: require(${JSON.stringify(item.requirePath)}),`);
}

lines.push(
  "};",
  "",
  "export const generatedIndividualImageKeys = Object.keys(monsterIndividualImages) as MonsterIndividualImageKey[];",
  "",
  "export const getIndividualImageParts = (",
  "  imageKey?: string",
  "): { speciesKey: string; variantKey: IndividualVariantKey } | undefined => {",
  "  if (!imageKey) {",
  "    return undefined;",
  "  }",
  "",
  "  const variantKey = INDIVIDUAL_VARIANT_KEYS.find((key) => imageKey.endsWith(`_${key}`));",
  "  if (!variantKey) {",
  "    return undefined;",
  "  }",
  "",
  "  return {",
  "    speciesKey: imageKey.slice(0, -1 * (`_${variantKey}`.length)),",
  "    variantKey",
  "  };",
  "};",
  "",
  "export const getIndividualImageBaseKey = (imageKey?: string): string | undefined =>",
  "  getIndividualImageParts(imageKey)?.speciesKey;",
  "",
  "export const getMonsterIndividualImageSource = (imageKey?: string): ImageSourcePropType | undefined => {",
  "  if (!imageKey) {",
  "    return undefined;",
  "  }",
  "",
  "  return monsterIndividualImages[imageKey as MonsterIndividualImageKey];",
  "};",
  "",
  "export const getGeneratedIndividualImageCount = (): number => generatedIndividualImageKeys.length;",
  "",
  "export const hasGeneratedIndividualImage = (speciesKey: string, variantKey: IndividualVariantKey): boolean =>",
  "  Boolean(monsterIndividualImages[makeIndividualImageKey(speciesKey, variantKey)]);",
  "",
  "export type IndividualVariantWithImage = IndividualVariant & {",
  "  imageKey: MonsterIndividualImageKey;",
  "  imageSource?: ImageSourcePropType;",
  "};",
  ""
);

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"), "utf8");

const total = speciesKeys.length * variantKeys.length;
console.log(`Generated manifest: ${outFile}`);
console.log(`Individual PNGs found: ${generated.length}/${total}`);
console.log("old/backup assets are intentionally ignored.");
