/**
 * server の character seed を「唯一の正本」から生成する（app catalog と同一ソース）。
 *   node scripts/generateServerSeed.js   (npm run gen:seed)
 *
 * 正本： assets/characters/character_master.json（+ rarity-overrides.json）＋実アセット。
 * 出力： server/src/characterSeed.generated.ts
 *
 * 初期リリースの母集団ルール（暫定・要承認）：
 *   「基本4ワールド（ground/waterside/sky/bug）」かつ「承認済みアセットが解決できる（hasImage）」キャラのみ。
 *   → server seed と app catalog が同じ正本から生成され、二度と 8体 vs 74体 のような乖離が起きない。
 *   phantom/planet 等の将来ワールド、画像未投入キャラは初期リリース対象外（監査で保留）。
 */
const fs = require("fs");
const path = require("path");

const { buildCatalog, loadClassification } = require("./catalogBuild");
const { assertGenerationSafe } = require("./masterGuards");

const root = path.join(__dirname, "..");
const charactersDir = path.join(root, "assets", "characters");
const master = JSON.parse(fs.readFileSync(path.join(charactersDir, "character_master.json"), "utf8"));
const classification = loadClassification(charactersDir);
const out = path.join(root, "server", "src", "characterSeed.generated.ts");

const built = buildCatalog({ root, charactersDir, master, classification });

// Phase 0 ガード：world混入 / 空欄・未知rarity / legendary潰れ / ID重複rarity / initial件数変動 / initial未登録ID を生成前に検出する。
assertGenerationSafe("gen:seed", { master, classification, built });

const { characters, rares, legendaries, missingInitialAssets: missing } = built;

// release gate（§14 原子性）：initial 画像欠損時は既定で中止し、server/app を不一致に部分再生成しない。
const allowIncomplete = process.env.WORLDAWN_ALLOW_INCOMPLETE === "1";
if (missing.length > 0 && !allowIncomplete) {
  console.error(`[gen:seed] initial 画像欠損 ${missing.length} 体のため中止（app catalog と同一集合から再生成するには4画像が必要）:`);
  for (const m of missing) console.error(`  - ${m.id} 期待パス: ${m.expectedPaths[0]}`);
  process.exit(2);
}

// server seed も buildable（initial かつ画像あり）＝app catalog と同一集合。
const pick = (arr, rarity) =>
  arr
    .filter((c) => c.releaseStatus === "initial" && c.hasImage)
    .map((c) => ({ id: c.id, name: c.name, rarity, world: c.worldGroup }));

const seed = [...pick(characters, "normal"), ...pick(rares, "rare"), ...pick(legendaries, "legendary")].sort((a, b) =>
  a.id < b.id ? -1 : a.id > b.id ? 1 : 0
);

const byWorldRarity = {};
for (const c of seed) {
  const k = `${c.world}/${c.rarity}`;
  byWorldRarity[k] = (byWorldRarity[k] || 0) + 1;
}

const lines = [];
lines.push("// AUTO-GENERATED by scripts/generateServerSeed.js. Do not edit by hand.");
lines.push("// 正本: assets/characters/character_master.json (+ rarity-overrides.json)。app catalog と同一ソース。");
lines.push("// 初期リリース母集団＝基本4ワールド ∩ 承認済みアセット(hasImage)。");
lines.push("");
lines.push("export type SeedCharacter = { id: string; name: string; rarity: string; world: string };");
lines.push("");
lines.push(`export const SEED_CHARACTERS: SeedCharacter[] = ${JSON.stringify(seed, null, 2)};`);
lines.push("");
fs.writeFileSync(out, lines.join("\n"), "utf8");

console.log(`[gen:seed] wrote ${path.relative(root, out)}  characters=${seed.length}`);
console.log("[gen:seed] by world/rarity:", JSON.stringify(byWorldRarity));
if (missing.length > 0) console.warn(`[gen:seed] 注意: initial 画像欠損 ${missing.length} 体（WORLDAWN_ALLOW_INCOMPLETE=1 で安全ビルド生成中）。`);
