/**
 * 効果音マニフェスト生成スクリプト。
 *
 *   node scripts/generateSoundManifest.js   （= npm run gen:sounds）
 *
 * assets/sounds/ を走査し、SoundId に対応する素材ファイルが存在するものだけ
 * require する src/assets/soundManifest.generated.ts を出力する。
 * 存在しないファイルを require するとバンドルが壊れるため、実在ファイルのみ載せる。
 *
 * 素材ファイル名の規約（拡張子は mp3 / m4a / wav の順で優先）:
 *   sound_ui_tap.mp3, sound_scan_success.mp3, ...
 *
 * このスクリプトは assets/sounds/ の中身を読むだけで、音素材を移動・変更しない。
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SOUNDS_DIR = path.join(ROOT, "assets", "sounds");
const OUT_FILE = path.join(ROOT, "src", "assets", "soundManifest.generated.ts");

// SoundId → ベース名（src/types/sound.ts の SOUND_FILE_BASENAMES と一致させる）。
const BASENAMES = {
  tap: "sound_ui_tap",
  cancel: "sound_ui_cancel",
  error: "sound_ui_error",
  scan_start: "sound_scan_start",
  scan_read: "sound_scan_read",
  scan_success: "sound_scan_success",
  discovery_normal: "sound_discovery_normal",
  discovery_rare: "sound_discovery_rare",
  discovery_legend: "sound_discovery_legend",
  discovery_secret: "sound_discovery_secret",
  dex_complete: "sound_dex_complete",
  rediscovery: "sound_rediscovery",
  dp_gain: "sound_dp_gain",
  world_unlock: "sound_world_unlock",
  boost_activate: "sound_boost_activate",
  title_unlock: "sound_title_unlock",
  favorite: "sound_favorite"
};

const EXT_PRIORITY = [".mp3", ".m4a", ".wav"];

const findFile = (base) => {
  for (const ext of EXT_PRIORITY) {
    const file = `${base}${ext}`;
    if (fs.existsSync(path.join(SOUNDS_DIR, file))) {
      return file;
    }
  }
  return null;
};

const entries = [];
const missing = [];
for (const [id, base] of Object.entries(BASENAMES)) {
  const file = findFile(base);
  if (file) {
    entries.push(`  ${id}: require("../../assets/sounds/${file}"),`);
  } else {
    missing.push(id);
  }
};

const header = `/**
 * AUTO-GENERATED by scripts/generateSoundManifest.js — DO NOT EDIT BY HAND.
 *
 * assets/sounds/ に配置済みの音素材だけを require する（存在しないファイルは
 * Metro のバンドルを壊すため、ここには載せない）。素材を追加したら
 *   npm run gen:sounds
 * を実行すると、この表に require が追記される。
 * 現在ここに載っていない SoundId は「無音（no-op）」として安全に扱われる。
 */
import type { SoundId } from "../types/sound";
`;

const body =
  entries.length > 0
    ? `\nexport const SOUND_SOURCES: Partial<Record<SoundId, number>> = {\n${entries.join("\n")}\n};\n`
    : `\nexport const SOUND_SOURCES: Partial<Record<SoundId, number>> = {\n  // 例: tap: require("../../assets/sounds/sound_ui_tap.mp3"),\n};\n`;

fs.writeFileSync(OUT_FILE, `${header}${body}`, "utf8");

console.log(`[gen:sounds] wrote ${path.relative(ROOT, OUT_FILE)}`);
console.log(`[gen:sounds] registered ${entries.length} sound(s).`);
if (missing.length > 0) {
  console.log(`[gen:sounds] not placed yet (silent): ${missing.join(", ")}`);
}
