/**
 * 新しいワールド構成のキャラクターデータを生成する。
 *
 * 入力:
 *   - assets/characters/character_master.json   … Character.xlsx から抽出した原本
 *       { "<world>": [ { no, name(キャラ名), speciesJa(和名), speciesEn(英名), rarity, status } ... ] }
 *   - assets/characters/<world>/<rarity>/<英名>.png または <world>/<英名>/<英名>.png … 実画像（存在するものだけ）
 *
 * 出力:
 *   - src/data/characterCatalog.generated.ts   … CATALOG_CHARACTERS / CATALOG_NORMALS / CATALOG_RARES / CATALOG_LEGENDARIES
 *   - src/assets/characterImages.generated.ts  … 実在PNGだけを static require する画像マニフェスト
 *
 * 方針:
 *   - 構築ロジックは scripts/catalogBuild.js（純粋・テスト可能）に集約。ここは file 書き出しとサムネ生成のみ。
 *   - Metro は動的requireできないので、画像は存在するものだけを静的requireする（欠損でバンドルが壊れない）。
 *   - 画像未生成のキャラも図鑑の枠として残す（hasImage=false）。
 */
const fs = require("fs");
const path = require("path");

const { buildCatalog } = require("./catalogBuild");

const root = path.join(__dirname, "..");
const charactersDir = path.join(root, "assets", "characters");
const masterPath = path.join(charactersDir, "character_master.json");
const catalogOut = path.join(root, "src", "data", "characterCatalog.generated.ts");
const imagesOut = path.join(root, "src", "assets", "characterImages.generated.ts");

const toPosix = (value) => value.split(path.sep).join("/");

const master = JSON.parse(fs.readFileSync(masterPath, "utf8"));
const { characters, rares, legendaries, imageEntries } = buildCatalog({ root, charactersDir, master });

const THUMB_MAX = 256; // 図鑑グリッド表示用サムネの最大辺(px)。表示は110px前後だがRetina/拡大に余裕を持たせる。
const thumbsDir = path.join(root, "assets", "thumbs");

// 大きな原画(1024px級)を図鑑用の小さいサムネに縮小する。原画より新しいサムネがあればスキップ。
const buildThumbnails = async (entries) => {
  const { Jimp } = require("jimp");
  fs.mkdirSync(thumbsDir, { recursive: true });
  const out = [];
  let made = 0;
  for (const e of entries) {
    const outAbs = path.join(thumbsDir, `${e.id}.png`);
    try {
      const srcStat = fs.statSync(e.abs);
      const fresh = fs.existsSync(outAbs) && fs.statSync(outAbs).mtimeMs >= srcStat.mtimeMs;
      if (!fresh) {
        const img = await Jimp.read(e.abs);
        const { width, height } = img.bitmap;
        const scale = THUMB_MAX / Math.max(width, height);
        if (scale < 1) {
          img.resize({ w: Math.max(1, Math.round(width * scale)), h: Math.max(1, Math.round(height * scale)) });
        }
        await img.write(outAbs);
        made += 1;
      }
      out.push({ id: e.id, requirePath: "../../" + toPosix(path.relative(root, outAbs)) });
    } catch (err) {
      console.warn(`  thumb skip ${e.id}: ${err.message}`);
    }
  }
  console.log(`thumbnails: ${out.length} ready (${made} regenerated)`);
  return out;
};

// ---------- write catalog ----------
const catalogLines = [];
catalogLines.push("// AUTO-GENERATED by scripts/generateCharacterData.js. Do not edit by hand.");
catalogLines.push("// worldGroup 構成のキャラクターメタデータ（画像requireは characterImages.generated.ts）。");
catalogLines.push("");
catalogLines.push("export type CatalogCharacter = {");
catalogLines.push("  id: string;");
catalogLines.push("  realmGroup: string;");
catalogLines.push("  worldGroup: string;");
catalogLines.push("  no: number;");
catalogLines.push("  name: string;");
catalogLines.push("  speciesJa: string;");
catalogLines.push("  speciesEn: string;");
catalogLines.push("  hasImage: boolean;");
catalogLines.push("  status: string;");
catalogLines.push("  description: string;");
catalogLines.push("};");
catalogLines.push("");
catalogLines.push("export type CatalogRare = {");
catalogLines.push("  id: string;");
catalogLines.push("  realmGroup: string;");
catalogLines.push("  worldGroup: string;");
catalogLines.push("  no: number;");
catalogLines.push("  name: string;");
catalogLines.push("  speciesJa: string;");
catalogLines.push("  speciesEn: string;");
catalogLines.push("  hasImage: boolean;");
catalogLines.push("  description: string;");
catalogLines.push("};");
catalogLines.push("");
catalogLines.push(`export const CATALOG_CHARACTERS: CatalogCharacter[] = ${JSON.stringify(characters, null, 2)};`);
catalogLines.push("");
// CATALOG_NORMALS は CATALOG_CHARACTERS の別名（normal 一覧）。段3で normal/rare/legendary を明示分離。
catalogLines.push("export const CATALOG_NORMALS: CatalogCharacter[] = CATALOG_CHARACTERS;");
catalogLines.push("");
catalogLines.push(`export const CATALOG_RARES: CatalogRare[] = ${JSON.stringify(rares, null, 2)};`);
catalogLines.push("");
// 伝説キャラ（段3）。UIは「そのワールドのnormalコンプリート後のみ」表示すること（未解放時は一切示唆しない）。
catalogLines.push(`export const CATALOG_LEGENDARIES: CatalogRare[] = ${JSON.stringify(legendaries, null, 2)};`);
catalogLines.push("");
fs.writeFileSync(catalogOut, catalogLines.join("\n"), "utf8");

// ---------- write image manifest（サムネ生成を含むため async） ----------
(async () => {
  const thumbEntries = await buildThumbnails(imageEntries);

  const imgLines = [];
  imgLines.push("// AUTO-GENERATED by scripts/generateCharacterData.js. Do not edit by hand.");
  imgLines.push("// 実在するPNGだけを static require（欠損画像はキーごと存在しない）。");
  imgLines.push("// CHARACTER_IMAGES=原画（個体詳細/結果用）、CHARACTER_THUMBS=図鑑グリッド用の縮小版。");
  imgLines.push('import type { ImageSourcePropType } from "react-native";');
  imgLines.push("");
  imgLines.push("export const CHARACTER_IMAGES: Record<string, ImageSourcePropType> = {");
  for (const e of imageEntries) {
    imgLines.push(`  ${JSON.stringify(e.id)}: require(${JSON.stringify(e.requirePath)}),`);
  }
  imgLines.push("};");
  imgLines.push("");
  imgLines.push("export const CHARACTER_THUMBS: Record<string, ImageSourcePropType> = {");
  for (const e of thumbEntries) {
    imgLines.push(`  ${JSON.stringify(e.id)}: require(${JSON.stringify(e.requirePath)}),`);
  }
  imgLines.push("};");
  imgLines.push("");
  imgLines.push("export const getCharacterImage = (id: string): ImageSourcePropType | undefined => CHARACTER_IMAGES[id];");
  imgLines.push("");
  imgLines.push("export const hasCharacterImage = (id: string): boolean => Boolean(CHARACTER_IMAGES[id]);");
  imgLines.push("");
  imgLines.push("// 図鑑用サムネ。無ければ原画へフォールバックできるよう undefined を返す。");
  imgLines.push("export const getCharacterThumb = (id: string): ImageSourcePropType | undefined =>");
  imgLines.push("  CHARACTER_THUMBS[id] ?? CHARACTER_IMAGES[id];");
  imgLines.push("");
  fs.writeFileSync(imagesOut, imgLines.join("\n"), "utf8");

  // ---------- summary ----------
  const byWorld = {};
  for (const c of characters) {
    byWorld[c.worldGroup] = byWorld[c.worldGroup] || { total: 0, img: 0 };
    byWorld[c.worldGroup].total += 1;
    if (c.hasImage) byWorld[c.worldGroup].img += 1;
  }
  console.log("Generated:", path.relative(root, catalogOut), "&", path.relative(root, imagesOut));
  console.log("characters:", characters.length, "rares:", rares.length, "legendaries:", legendaries.length, "images bundled:", imageEntries.length);
  for (const [wg, s] of Object.entries(byWorld)) {
    console.log(`  ${wg}: ${s.img}/${s.total} images`);
  }
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
