const fs = require("fs");
const path = require("path");

// リポジトリルート（scripts/ の1つ上）。
const root = path.join(__dirname, "..");
const formsDir = path.join(root, "assets", "characters", "forms");
const outFile = path.join(root, "src", "assets", "monsterFormImages.ts");

const STAGES = ["kou", "sai", "sei", "gen", "gyo"];

/** assets/characters/forms/<species>/*.png を走査し、実在ファイルだけを require する。 */
const collect = () => {
  const entries = [];
  if (!fs.existsSync(formsDir)) {
    return entries;
  }

  for (const species of fs.readdirSync(formsDir)) {
    const speciesDir = path.join(formsDir, species);
    if (!fs.statSync(speciesDir).isDirectory()) {
      continue;
    }

    for (const file of fs.readdirSync(speciesDir)) {
      if (!file.endsWith(".png")) {
        continue;
      }
      // ファイル名末尾の stage が対象キーのものだけ採用する。
      const key = file.replace(/\.png$/, "");
      const stage = STAGES.find((s) => key.endsWith(`_${s}`));
      if (!stage) {
        continue;
      }
      entries.push({
        key,
        requirePath: `../../assets/characters/forms/${species}/${file}`
      });
    }
  }

  entries.sort((a, b) => a.key.localeCompare(b.key));
  return entries;
};

const entries = collect();

const lines = [
  'import type { ImageSourcePropType } from "react-native";',
  "",
  'import type { FormStage } from "../types/economy";',
  'import type { IndividualVariantKey } from "../types/monster";',
  "",
  "// This file is generated by scripts/generateFormImages.js. Do not edit by hand.",
  "// Only existing PNGs are required so Metro never tries to bundle a missing file.",
  "export const monsterFormImages: Record<string, ImageSourcePropType> = {"
];

for (const entry of entries) {
  lines.push(`  ${JSON.stringify(entry.key)}: require(${JSON.stringify(entry.requirePath)}),`);
}

lines.push(
  "};",
  "",
  "export const getFormImageSource = (",
  "  speciesKey: string,",
  "  variantKey: IndividualVariantKey | undefined,",
  "  stage: FormStage",
  "): ImageSourcePropType | undefined => {",
  '  if (stage === "base") {',
  "    return undefined;",
  "  }",
  "",
  "  if (variantKey) {",
  "    const variantLevel = monsterFormImages[`${speciesKey}_${variantKey}_${stage}`];",
  "    if (variantLevel) {",
  "      return variantLevel;",
  "    }",
  "  }",
  "",
  "  return monsterFormImages[`${speciesKey}_${stage}`];",
  "};",
  "",
  "export const hasFormImage = (",
  "  speciesKey: string,",
  "  variantKey: IndividualVariantKey | undefined,",
  "  stage: FormStage",
  "): boolean => Boolean(getFormImageSource(speciesKey, variantKey, stage));",
  ""
);

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`Generated form-image manifest: ${outFile}`);
console.log(`Form PNGs found: ${entries.length}`);
