const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const charactersDir = path.join(root, "assets", "characters");
const outFile = path.join(root, "src", "assets", "characterFrames.ts");

const MOTION_NAMES = [
  "scan_appear",
  "detail_appear",
  "idle",
  "normal",
  "click_01_happy",
  "click_02_surprise",
  "click_03_affection"
];

const IGNORED_ROOT_DIRS = new Set(["old", "backup"]);

const DEFAULT_FRAME_DURATION = {
  scan_appear: 90,
  detail_appear: 100,
  idle: 150,
  normal: 120,
  click_01_happy: 85,
  click_02_surprise: 85,
  click_03_affection: 85
};

const toPosix = (value) => value.split(path.sep).join("/");

const numericSort = (a, b) => {
  const na = parseInt(a.replace(/\D/g, ""), 10);
  const nb = parseInt(b.replace(/\D/g, ""), 10);
  if (Number.isNaN(na) || Number.isNaN(nb)) {
    return a.localeCompare(b);
  }
  return na - nb;
};

const getSubdirectories = (dir) => {
  if (!fs.existsSync(dir)) {
    return [];
  }

  return fs
    .readdirSync(dir)
    .map((entry) => path.join(dir, entry))
    .filter((entryPath) => fs.statSync(entryPath).isDirectory());
};

const findCharacterDirs = () => {
  const result = [];

  for (const worldDir of getSubdirectories(charactersDir)) {
    const worldName = path.basename(worldDir);
    if (IGNORED_ROOT_DIRS.has(worldName)) {
      continue;
    }

    for (const characterDir of getSubdirectories(worldDir)) {
      result.push(characterDir);
    }
  }

  return result;
};

const readManifest = (characterDir) => {
  const manifestPath = path.join(characterDir, "manifest.json");
  if (!fs.existsSync(manifestPath)) {
    return {};
  }

  try {
    return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  } catch {
    return {};
  }
};

const listFrames = (motionDir) => {
  if (!fs.existsSync(motionDir) || !fs.statSync(motionDir).isDirectory()) {
    return [];
  }

  return fs
    .readdirSync(motionDir)
    .filter((file) => file.toLowerCase().endsWith(".png"))
    .sort(numericSort)
    .map((file) => path.join(motionDir, file));
};

const clampFrameDuration = (ms) => Math.max(60, Math.min(200, Math.round(ms)));

const buildCharacter = (characterDir) => {
  const manifest = readManifest(characterDir);
  const characterId = manifest.character_id || path.basename(characterDir);
  const motions = {};

  for (const motion of MOTION_NAMES) {
    const files = listFrames(path.join(characterDir, motion));
    if (files.length === 0) {
      continue;
    }

    const meta = (manifest.motions && manifest.motions[motion]) || {};
    const frameDuration = meta.fps
      ? clampFrameDuration(1000 / meta.fps)
      : DEFAULT_FRAME_DURATION[motion] || 110;
    const loop = Boolean(meta.loop);
    const interval = meta.interval_seconds
      ? { min: Number(meta.interval_seconds.min) || 4, max: Number(meta.interval_seconds.max) || 8 }
      : undefined;

    motions[motion] = {
      frameDuration,
      loop,
      interval,
      requirePaths: files.map((absolutePath) => "../../" + toPosix(path.relative(root, absolutePath)))
    };
  }

  if (Object.keys(motions).length === 0) {
    return null;
  }

  let shadowRel;
  const shadowCandidates = [];
  if (manifest.shadows && manifest.shadows.base) {
    shadowCandidates.push(path.join(characterDir, manifest.shadows.base));
  }
  shadowCandidates.push(path.join(characterDir, "base", "shadow.png"));

  for (const candidate of shadowCandidates) {
    if (fs.existsSync(candidate)) {
      shadowRel = "../../" + toPosix(path.relative(root, candidate));
      break;
    }
  }

  return { characterId, motions, shadowRel };
};

const characters = findCharacterDirs()
  .map(buildCharacter)
  .filter(Boolean)
  .sort((a, b) => a.characterId.localeCompare(b.characterId));

const lines = [];
lines.push("// AUTO-GENERATED by scripts/generateCharacterFrames.js. Do not edit by hand.");
lines.push("// Only existing frame PNGs are required so Metro never tries to bundle a missing file.");
lines.push('import type { ImageSourcePropType } from "react-native";');
lines.push("");
lines.push(
  'export type MotionName =\n  | "scan_appear"\n  | "detail_appear"\n  | "idle"\n  | "normal"\n  | "click_01_happy"\n  | "click_02_surprise"\n  | "click_03_affection";'
);
lines.push("");
lines.push("export type FrameMotion = {");
lines.push("  frames: ImageSourcePropType[];");
lines.push("  frameDuration: number;");
lines.push("  loop: boolean;");
lines.push("  interval?: { min: number; max: number };");
lines.push("};");
lines.push("");
lines.push("export type CharacterFrameSet = {");
lines.push("  characterId: string;");
lines.push("  motions: Partial<Record<MotionName, FrameMotion>>;");
lines.push("  shadow?: ImageSourcePropType;");
lines.push("};");
lines.push("");
lines.push("export const CHARACTER_FRAMES: Record<string, CharacterFrameSet> = {");

for (const character of characters) {
  lines.push(`  ${JSON.stringify(character.characterId)}: {`);
  lines.push(`    characterId: ${JSON.stringify(character.characterId)},`);
  lines.push("    motions: {");
  for (const motion of MOTION_NAMES) {
    const data = character.motions[motion];
    if (!data) {
      continue;
    }
    lines.push(`      ${motion}: {`);
    lines.push("        frames: [");
    for (const requirePath of data.requirePaths) {
      lines.push(`          require(${JSON.stringify(requirePath)}),`);
    }
    lines.push("        ],");
    lines.push(`        frameDuration: ${data.frameDuration},`);
    lines.push(`        loop: ${data.loop},`);
    if (data.interval) {
      lines.push(`        interval: { min: ${data.interval.min}, max: ${data.interval.max} },`);
    }
    lines.push("      },");
  }
  lines.push("    },");
  if (character.shadowRel) {
    lines.push(`    shadow: require(${JSON.stringify(character.shadowRel)}),`);
  }
  lines.push("  },");
}

lines.push("};");
lines.push("");
lines.push("export const getCharacterFrameSet = (characterId: string): CharacterFrameSet | undefined =>");
lines.push("  CHARACTER_FRAMES[characterId];");
lines.push("");
lines.push("export const hasCharacterFrames = (characterId: string): boolean =>");
lines.push("  Boolean(CHARACTER_FRAMES[characterId]);");
lines.push("");

fs.writeFileSync(outFile, lines.join("\n"), "utf8");

const summary = characters.map((item) => `${item.characterId}(${Object.keys(item.motions).length} motions)`).join(", ");
console.log(`Generated character-frame manifest: ${outFile}`);
console.log(`Characters with frames: ${characters.length}${summary ? " -> " + summary : ""}`);
