// AUTO-GENERATED by scripts/generateCharacterFrames.js. Do not edit by hand.
// Only existing frame PNGs are required so Metro never tries to bundle a missing file.
import type { ImageSourcePropType } from "react-native";

export type MotionName =
  | "scan_appear"
  | "detail_appear"
  | "idle"
  | "normal"
  | "click_01_happy"
  | "click_02_surprise"
  | "click_03_affection";

export type FrameMotion = {
  frames: ImageSourcePropType[];
  frameDuration: number;
  loop: boolean;
  interval?: { min: number; max: number };
};

export type CharacterFrameSet = {
  characterId: string;
  motions: Partial<Record<MotionName, FrameMotion>>;
  shadow?: ImageSourcePropType;
};

export const CHARACTER_FRAMES: Record<string, CharacterFrameSet> = {
};

export const getCharacterFrameSet = (characterId: string): CharacterFrameSet | undefined =>
  CHARACTER_FRAMES[characterId];

export const hasCharacterFrames = (characterId: string): boolean =>
  Boolean(CHARACTER_FRAMES[characterId]);
