import type { ImageSourcePropType } from "react-native";

import type { FormStage } from "../types/economy";
import type { IndividualVariantKey } from "../types/monster";

// This file is generated by scripts/generateFormImages.js. Do not edit by hand.
// Only existing PNGs are required so Metro never tries to bundle a missing file.
export const monsterFormImages: Record<string, ImageSourcePropType> = {
};

export const getFormImageSource = (
  speciesKey: string,
  variantKey: IndividualVariantKey | undefined,
  stage: FormStage
): ImageSourcePropType | undefined => {
  if (stage === "base") {
    return undefined;
  }

  if (variantKey) {
    const variantLevel = monsterFormImages[`${speciesKey}_${variantKey}_${stage}`];
    if (variantLevel) {
      return variantLevel;
    }
  }

  return monsterFormImages[`${speciesKey}_${stage}`];
};

export const hasFormImage = (
  speciesKey: string,
  variantKey: IndividualVariantKey | undefined,
  stage: FormStage
): boolean => Boolean(getFormImageSource(speciesKey, variantKey, stage));
