import type { ImageSourcePropType } from "react-native";

import { INDIVIDUAL_VARIANT_KEYS, type IndividualVariant } from "../data/individualVariants";
import type { IndividualVariantKey } from "../types/monster";

export type MonsterIndividualImageKey = `${string}_${IndividualVariantKey}`;

export const makeIndividualImageKey = (
  speciesKey: string,
  variantKey: IndividualVariantKey
): MonsterIndividualImageKey => `${speciesKey}_${variantKey}` as MonsterIndividualImageKey;

// This file is generated by scripts/generateMonsterImages.js.
// It scans assets/characters/<world>/<English>/ recursively and ignores old/backup.
// Only existing PNGs are required so Metro never tries to bundle a missing file.
export const monsterIndividualImages: Partial<Record<MonsterIndividualImageKey, ImageSourcePropType>> = {
};

export const generatedIndividualImageKeys = Object.keys(monsterIndividualImages) as MonsterIndividualImageKey[];

export const getIndividualImageParts = (
  imageKey?: string
): { speciesKey: string; variantKey: IndividualVariantKey } | undefined => {
  if (!imageKey) {
    return undefined;
  }

  const variantKey = INDIVIDUAL_VARIANT_KEYS.find((key) => imageKey.endsWith(`_${key}`));
  if (!variantKey) {
    return undefined;
  }

  return {
    speciesKey: imageKey.slice(0, -1 * (`_${variantKey}`.length)),
    variantKey
  };
};

export const getIndividualImageBaseKey = (imageKey?: string): string | undefined =>
  getIndividualImageParts(imageKey)?.speciesKey;

export const getMonsterIndividualImageSource = (imageKey?: string): ImageSourcePropType | undefined => {
  if (!imageKey) {
    return undefined;
  }

  return monsterIndividualImages[imageKey as MonsterIndividualImageKey];
};

export const getGeneratedIndividualImageCount = (): number => generatedIndividualImageKeys.length;

export const hasGeneratedIndividualImage = (speciesKey: string, variantKey: IndividualVariantKey): boolean =>
  Boolean(monsterIndividualImages[makeIndividualImageKey(speciesKey, variantKey)]);

export type IndividualVariantWithImage = IndividualVariant & {
  imageKey: MonsterIndividualImageKey;
  imageSource?: ImageSourcePropType;
};
