/**
 * AUTO-GENERATED by scripts/generateSoundManifest.js — DO NOT EDIT BY HAND.
 *
 * assets/sounds/ に配置済みの音素材だけを require する（存在しないファイルは
 * Metro のバンドルを壊すため、ここには載せない）。素材を追加したら
 *   npm run gen:sounds
 * を実行すると、この表に require が追記される。
 * 現在ここに載っていない SoundId は「無音（no-op）」として安全に扱われる。
 */
import type { SoundId } from "../types/sound";

export const SOUND_SOURCES: Partial<Record<SoundId, number>> = {
  // 例: tap: require("../../assets/sounds/sound_ui_tap.mp3"),
};
